// <auto-generated />
using System;
using MedManage.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedManage.Infrastructure.Migrations
{
    [DbContext(typeof(MedManageDbContext))]
    [Migration("20250628120000_UpdateLetterTemplatesWithTariffPlaceholders")]
    partial class UpdateLetterTemplatesWithTariffPlaceholders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedManage.Core.Entities.TariffPercentage", b =>
                {
                    b.Property<int>("TariffPercentageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TariffPercentageId"));

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateInserted")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime");

                    b.Property<DateOnly?>("EndActiveDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("PercentageAdded")
                        .HasColumnType("decimal(10, 4)");

                    b.Property<int?>("RecordsAffected")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartActiveDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TariffPeriodName")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedUserID")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedUserID");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserID");

                    b.HasKey("TariffPercentageId");

                    b.HasIndex("TariffPeriodName", "EndActiveDate")
                        .HasDatabaseName("IX_TariffPercentage_TariffPeriodName_EndActiveDate");

                    b.HasIndex("TariffPeriodName", "StartActiveDate")
                        .HasDatabaseName("IX_TariffPercentage_TariffPeriodName_StartActiveDate");

                    b.ToTable("TariffPercentage", "Tariff");
                });
#pragma warning restore 612, 618
        }
    }
}
